//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LfS.GestureDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceInfo> DeviceInfos { get; set; }
        public virtual DbSet<Gesture> Gestures { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<Touch> Touches { get; set; }
        public virtual DbSet<TouchField> TouchFields { get; set; }
        public virtual DbSet<Trace> Traces { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
