//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LfS.GestureDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trace()
        {
            this.Symbols = new HashSet<Symbol>();
            this.Touches = new HashSet<Touch>();
        }
    
        public long Id { get; set; }
        public long Gesture_Id { get; set; }
        public long DeviceInfo_Id { get; set; }
        public long TouchField_Id { get; set; }
    
        public virtual DeviceInfo DeviceInfo { get; set; }
        public virtual Gesture Gesture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symbol> Symbols { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Touch> Touches { get; set; }
        public virtual TouchField TouchField { get; set; }
    }
}
